// Generated by Finicky Kickstart 
// Save as ~/.finicky.js

module.exports = {
  defaultBrowser: "Safari",      
  handlers: [
    {
      match: /^https?:\/\/zoom\.us\/.*$/,
      browser: "Google Chrome"
    },
    {
      match: /^https?:\/\/docs\.google\.com\/.*$/,
      browser: "Google Chrome"
    },
    {
      match: /^https?:\/\/dndbeyond\.com\/.*$/,
      browser: "Google Chrome"
    }
  ]
}
